### ISSUE TITLE
Lack of treatment for circular structures

### ISSUE THREAD

**Issue by vxksf** [herbsjs/herbs#1]
**Describe the bug**
The Step class uses JSON.stringify without the callback function to handle circular structures. When passing an object with a circular structure it shows the error "TypeError: Converting circular structure to JSON" and interrupts code execution.

**To Reproduce**

1. Create a usecase and use the step method on it.
2. Create an object with a circular structure, for example by creating a spreadsheet with exceljs.
3. Try passing the created spreadsheet from one step to another inside usecase
4. See the error
 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Worksheet'
    |     property '_rows' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Row'
    --- property '_worksheet' closes the circle

**Expected behavior**
The Setp class should perform the packaging of objects with circular structures.

**Screenshots**
Object with circular reference
![image](https://user-images.githubusercontent.com/80110798/129958487-d223e00c-2dbf-4c95-bf55-c89a9ea7176e.png)

The output error
![image](https://user-images.githubusercontent.com/80110798/129958083-223d9430-58a4-4458-8942-ec1928f42b74.png)

**Additional context**
n/a

**Comment by maikvortx** [comment]
Hi Kevin, this is an old bug in Herbs and we have many projects with this issue. What can we apply to solve this problem? Do you already have a solution in mind?

**Comment by vxksf** [comment]
Hello Maik, 

Yeah, i have one.

We should add a replacer function in the second parameter of the function JSON.stringify and, of course, set that replacer function for treat circular structures.

I just fixed that bug e open the following pull request:
https://github.com/herbsjs/buchu/pull/47

By the way, i create this issue in the buchu repo as well, i think there is the rigth place for this issue. The issue is here:
https://github.com/herbsjs/buchu/issues/46

Thanks.
