### ISSUE TITLE
Create a XLSX spreadsheet glue from the output of an USECASE

### ISSUE THREAD

**Issue by MarcioFWeb** [herbsjs/herbs#21]
**Is your feature request related to a problem? Please describe.**

Its a suggestion: create a glue for Herbs, to generate and make available spreadsheet files in XLSX format from the output data of the USE CASES processing.

**Describe the solution you'd like**

Create a glue for Herbs that generates from the output data of USE CASE processing, generates and makes available files in XLSX format ("Office Open XML" spreadsheet).

BENEFITS OF THIS GLUE:
* Standardize, simplify and abstract the work of this generation of XLSX.
* Faster development speed.
* Provide solution for this type of requirement in projects.

**Describe alternatives you've considered**

The alternative is to generate XLSX spreadsheets manually, usually using one of the many libraries available.

**Additional context**

Some references about XLSX:

- [XLSX Strict (Office Open XML), ISO 29500-1:2008-2016](https://www.loc.gov/preservation/digital/formats/fdd/fdd000401.shtml)
- [ECMA-376](https://www.ecma-international.org/publications-and-standards/standards/ecma-376/)
- [Microsoft](https://docs.microsoft.com/en-us/deployoffice/compat/xml-file-name-extension-reference-for-office)

**Comment by italojs** [comment]
how did you image the usage? could you provide some code example?

**Comment by MarcioFWeb** [comment]
Hello Italo. Of course, I share a case with you.

In some projects that we develop, using HerbsJS, we need to export date generated in a step of a usecase, in a XLSX file.

There are several squads, several projects, several problems. In common: we use HerbsJS.

So, I believe it would be very interesting to have a glue for Herbs that would assume this responsibility and bridge the gap in providing the output of a step or usecase, in XLSX format in a standardized way, without using different libraries, reducing external dependencies, decreasing complexity, increasing delivery speed.

**Examples:**

**Here is an excerpt of some STEPS from a USECASE, where a class with the responsibility of generating the XLSX is called:**

`Create the WorkBook in .xlsx template and include the movement date': step(async ctx => {
      try {
        const excelService = new dateFileExcelService()
        const movements = await ctx.validMovements

        ctx.workbook = await excelService.init('worksheet name')
        ctx.workbook = await excelService.setHeader('./worksheet_logo.png', 'worksheet name')
        ctx.workbook = await excelService.includemovements(movements, ctx.outputdate)

        ctx.ret.workbook = ctx.workbook.wb

        return Ok('XLSX created')
      } catch (error) {
        kinesisFirehoseLogger.error('Create movements XLSX', error)
        return Err(error)
      }
    }),
    'Send the .xlsx file in base64': step(async ctx => {
      try {
        let { workbook } = ctx.ret
        const date = new Date().getDate() + '.' +  new Date().getMonth() + 1 + '.' + new Date().getFullYear()
        const fileName = 'excel_data_filename'
        
        ctx.ret = new ctx.di.FileWriteStream()
        ctx.ret.name = `RETURN - ${fileName} - ${date}.xlsx`

        const path = `temp/${ctx.ret.name}`
        await ctx.ret.writePromisify(workbook, path)
        ctx.ret.readFileSync(path)

        return Ok()
      } catch (error) {
        kinesisFirehoseLogger.error('Send XLSX file in base64', error)
        return Err(error)
      }
    })`	

**And here is a snippet of this class, considering the dependency on external libraries:**

`import xlsx from 'excel4node'
import ATypeEnum from '../domain/valueObjects/ATypeEnum'
import stringFormatter from '../helpers/stringFormatter'

class MovementFileExcelService {
  constructor(worksheet) {
    this.worksheet = worksheet
  }
  init = async worksheetName => {
    const workbook = new xlsx.Workbook()
    this.worksheet = workbook.addWorksheet(worksheetName)
    return workbook
  }

  setHeader = async (image, title) => {
    const titleStyle = { font: { bold: true, color: 'cb1e25', size: 20 } }
    const headerStyle = {
      font: { bold: true, color: 'cb1e25' },
      alignment: { horizontal: 'center' },
      border: {
        left: { style: 'medium', color: 'c4c4c4' },
        right: { style: 'medium', color: 'c4c4c4' },
        top: { style: 'medium', color: 'c4c4c4' },
        bottom: { style: 'medium', color: 'c4c4c4' }
      }
    }

    this.worksheet.column(1).setWidth(30)
    this.worksheet.column(2).setWidth(30)
    this.worksheet.column(3).setWidth(30)
    this.worksheet.column(4).setWidth(30)
    this.worksheet.column(5).setWidth(30)
    this.worksheet.column(6).setWidth(30)
    this.worksheet.column(7).setWidth(30)
    this.worksheet.column(8).setWidth(30)
    this.worksheet.column(9).setWidth(30)
    this.worksheet.column(10).setWidth(30)

    this.worksheet.addImage({ path: image, type: 'picture', position: { type: 'absoluteAnchor', x: '210mm', y: '4mm' } })

    this.worksheet.cell(1, 1, 1, 10).style({
      fill: {
        type: 'pattern',
        patternType: 'solid',
        fgColor: 'cb2e25'
      }
    })
    this.worksheet.cell(2, 1, 6, 10).style({
      fill: {
        type: 'pattern',
        patternType: 'solid',
        fgColor: 'ffffff'
      }
    })
    this.worksheet
      .cell(5, 4)
      .string(title)
      .style(titleStyle)

    this.worksheet
      .cell(7, 1)
      .string('column title')
      .style(headerStyle)
    this.worksheet
      .cell(7, 2)
      .string('column title')
      .style(headerStyle)
    this.worksheet
      .cell(7, 3)
      .string('column title')
      .style(headerStyle)
    this.worksheet
      .cell(7, 4)
      .string('column title')
      .style(headerStyle)
    this.worksheet
      .cell(7, 5)
      .string('column title')
      .style(headerStyle)    

    return this.worksheet
  }

  includemovements = async (movements, oneDomainObject) => {
    movements.map((item, index) => {
      const row = index + 8

      this.worksheet
        .cell(row, 1)
        .date(oneDomainObject.sendDate)
        .style({ numberFormat: 'yyyy/mm/dd' })
      this.worksheet.cell(row, 2).string(item.oneAttribute)
      this.worksheet.cell(row, 5).string(stringFormatter.removeMask(item.product))
      this.worksheet.cell(row, 6).string(ATypeEnum[item.optionData])
      this.worksheet
        .cell(row, 7)
        .number(item.valor)
        .style({ numberFormat: '###,###,###.00' })

      if (item.optionData === 'A') {
        this.worksheet
          .cell(row, 8)
          .date(item.endDate)
          .style({ numberFormat: 'yyyy/mm/dd' })
        this.worksheet.cell(row, 9).string('-')
        this.worksheet.cell(row, 10).string('-')
      } else {
        this.worksheet.cell(row, 8).string('-')
        this.worksheet
          .cell(row, 9)
          .date(item.startDate)
          .style({ numberFormat: 'yyyy/mm/dd' })
        this.worksheet
          .cell(row, 10)
          .date(item.middleDate)
          .style({ numberFormat: 'yyyy/mm/dd' })
      }
    })
    return this.worksheet
  }
}

export default MovementFileExcelService`

We also have other examples. Different implementations to solve the same problem. (And this is not good)

Thank you for your attention and congratulations for the work here.

Looking forward to contributing soon.

**Comment by MarcioFWeb** [comment]
Hello Italo. Of course, I share a case with you.

In some projects that we develop, using HerbsJS, we need to export date generated in a step of a usecase, in a XLSX file.

There are several squads, several projects, several problems. In common: we use HerbsJS.

So, I believe it would be very interesting to have a glue for Herbs that would assume this responsibility and bridge the gap in providing the output of a step or usecase, in XLSX format in a standardized way, without using different libraries, reducing external dependencies, decreasing complexity, increasing delivery speed.

Examples:

Here is an excerpt of some STEPS from a USECASE, where a class with the responsibility of generating the XLSX is called:

`
Create the WorkBook in .xlsx template and include the movement date": step(async ctx => {
      try {
        const excelService = new dateFileExcelService()
        const movements = await ctx.validMovements

        ctx.workbook = await excelService.init("worksheet name")
        ctx.workbook = await excelService.setHeader("./worksheet_logo.png", "worksheet name")
        ctx.workbook = await excelService.includemovements(movements, ctx.outputdate)

        ctx.ret.workbook = ctx.workbook.wb

        return Ok("XLSX created")
      } catch (error) {
        kinesisFirehoseLogger.error("Create movements XLSX", error)
        return Err(error)
      }
    }),
    "Send the .xlsx file in base64": step(async ctx => {
      try {
        let { workbook } = ctx.ret
        const date = new Date().getDate() + "." +  new Date().getMonth() + 1 + "." + new Date().getFullYear()
        const fileName = "excel_data_filename"
        
        ctx.ret = new ctx.di.FileWriteStream()
        ctx.ret.name = `RETURN - ${fileName} - ${date}.xlsx`

        const path = `temp/${ctx.ret.name}`
        await ctx.ret.writePromisify(workbook, path)
        ctx.ret.readFileSync(path)

        return Ok()
      } catch (error) {
        kinesisFirehoseLogger.error("Send XLSX file in base64", error)
        return Err(error)
      }
    })
`

**Comment by MarcioFWeb** [comment]
Hello Italo. Of course, I share a case with you.

In some projects that we develop, using HerbsJS, we need to export date generated in a step of a usecase, in a XLSX file.

There are several squads, several projects, several problems. In common: we use HerbsJS.

So, I believe it would be very interesting to have a glue for Herbs that would assume this responsibility and bridge the gap in providing the output of a step or usecase, in XLSX format in a standardized way, without using different libraries, reducing external dependencies, decreasing complexity, increasing delivery speed.

**Examples:**

**Here is an excerpt of some STEPS from a USECASE, where a class with the responsibility of generating the XLSX is called:**

`USECASE`

> [USECASE EXAMPLE](https://carbon.now.sh/PsSYA73vT3vlqtrQdrZg)	

**And here is a snippet of this class, considering the dependency on external libraries:**

> [EXAMPLE CLASS](https://carbon.now.sh/70PQ59DUn5zMPvsK9Iyr)

We also have other examples. Different implementations to solve the same problem. (And this is not good)

Thank you for your attention and congratulations for the work here.

Looking forward to contributing soon.

**Comment by italojs** [comment]
your matrix that you want to convert to a xlsx is a usecase data, not an usecase metadata, I see it is more related to a lib then a herbs glue, you could to create a library that dont use herbs metadata that receive an matrix and prepare it for a XLSX file and it will works for all projects in the world.

**Comment by italojs** [comment]
issue abandoned
