### ISSUE TITLE
A suggestion to improve code generation

### ISSUE THREAD

**Issue by Conrage** [herbsjs/herbs#35]
A framework, [sails](https://github.com/balderdashy/sails) has a similar CRUD code generation, maybe it's a good example to help you develop and improve this part of the project!

**Comment by Conrage** [comment]
> Hi @Conrage , thank you for the comment. 
> 
> Have you tried `herbs cli` (https://github.com/herbsjs/herbs-cli)? It might be what you are looking for.
> 
> If yes, is there any specific feature you would like to see on Herbs or CLI?

Actually i haven't had any problems using herbs cli or anything related, just came to my knowledge you guys were starting on this code generating stuff, so i created this issue just to help

**Comment by dalssoft** [comment]
@Conrage, thank you for the feedback. Let us know if there is any issue or specific feature you would like to see on Herbs.

Since there is no action here, I'm closing this issue.
