### ISSUE TITLE
Metadata - Different DX

### ISSUE THREAD

**Issue by jhomarolo** [herbsjs/herbs#4]
Brainstorm from @dalssoft:

I've been thinking about the developer experience when dealing with glues. Although it is correct to have a folder and files for each glue (ex: graphQL and REST) from the architecture point of view, it doesn't make it clear the idea of metadata to developers.

Thinking about that I created a different way to specify the metadata:

(1) You would have a folder \infra\meta\...
https://user-images.githubusercontent.com/209287/122963117-5e735200-d35c-11eb-996a-4e710618f243.png

(2) Meta for Entities
https://user-images.githubusercontent.com/209287/122962983-413e8380-d35c-11eb-99d1-cad70bd9f797.png

(2) Meta for Usecases
https://user-images.githubusercontent.com/209287/122963058-52879000-d35c-11eb-8315-19328a175fd1.png

Different approachs come to my mind but I think this one is the one I like most. What do you think?

**Comment by dalssoft** [comment]
Given now we have Herbarium I don't think this issue is relevant any longer.
